connector.name=druid
connection-url=jdbc:avatica:remote:url=http://druid-broker.prod.internal:8082/druid/v2/sql/avatica/;transparent_reconnection=true
connection-user=druid_internal
connection-password=
case-insensitive-name-matching=true
query.pushdown.enabled=true
druid.broker-url=http://druid-broker.prod.internal:8082
druid.coordinator-url=http://druid-coordinator.prod.internal:8081
druid.schema=druid
druid.compute-pushdown-enabled=true
